title: Niyi Ogunkunle
logo: /assets/img/headshot_circle.png
#description: Data Analyst | Transforming Complex Data into Actionable Insights for Business Growth
show_downloads: true
theme: jekyll-theme-minimal
