title: Niyi Ogunkunle
logo: /Niyi passport pix.png
#description: Data Analyst | Transforming Complex Data into Actionable Insights for Business Growth
show_downloads: true
theme: jekyll-theme-minimal
